export default {
    "Weiler": 1,
    "Dorf": 2,
    "Kleinstadt": 3,
    "Kleine Stadt": 4,
    "Mittelstadt": 5,
    "Großstadt": 6,
    "Metropole": 7,
    "Aldea": 1,
    "Pueblo": 2,
    "Villa": 3,
    "Pequeña ciudad": 4,
    "Ciudad mediana": 5,
    "Gran ciudad": 6,
    "Metrópoli": 7,
    "Hamlet": 1,
    "Village": 2,
    "Small town": 3,
    "Town": 4,
    "Medium-sized city": 5,
    "Large city": 6,
    "Metropolis": 7,
    "Hameau": 1,
    "Village": 2,
    "Bourg": 3,
    "Petite ville": 4,
    "Ville moyenne": 5,
    "Grande ville": 6,
    "Métropole": 7,
}