export default {
    "Municipalidad": 1,
    "Asociación": 2,
    "Organismo privado": 3,
    "Particular": 4,
    "No sabe": 5,
    "Municipalité": 1,
    "Association": 2,
    "Organisme privé": 3,
    "Particulier": 4,
    "Ne sait pas": 5,
    "Municipality": 1,
    "Association": 2,
    "Private organization": 3,
    "Individual": 4,
    "Do not know": 5,
    "Gemeinde": 1,
    "Verein": 2,
    "Privatorganisation": 3,
    "Privatperson": 4,
    "Weiß nicht": 5
}