export default {
    "Sin limpieza": 1,
    "Raramente": 2,
    "Ocasionalmente": 3,
    "Regularmente": 4,
    "Diariamente": 5,
    "No sabe": 6,
    "Pas de nettoyage": 1,
    "Rarement": 2,
    "Occasionnellement": 3,
    "Régulièrement": 4,
    "Journalier": 5,
    "Ne sait pas": 6,
    "No cleaning": 1,
    "Rarely": 2,
    "Occasionally": 3,
    "Regularly": 4,
    "Daily": 5,
    "Do not know": 6,
    "Keine Reinigung": 1,
    "Selten": 2,
    "Gelegentlich": 3,
    "Regelmäßig": 4,
    "Täglich": 5,
    "Weiß nicht": 6
}