export default {
    "Leisure": 1,
    "Fishing": 2,
    "Leisure and fishing": 3,
    "Other": 4,
    "Do not know": 5,
    "Plaisance": 1,
    "Pêche": 2,
    "Plaisance et pêche": 3,
    "Autre": 4,
    "Ne sait pas": 5,
    "Freizeit": 1,
    "Fischerei": 2,
    "Freizeit und Fischerei": 3,
    "Anderer": 4,
    "Weiß nicht": 5,
    "Recreativo": 1,
    "Pesca": 2,
    "Recreativo y pesca": 3,
    "Otro": 4,
    "No sabe": 5,
}