export default {
    "Flood": 2,
    "Heavy rains": 3,
    "Storm": 4,
    "Hurricane": 5,
    "Other": 6,
    "Do not know": 7,
    "Crue": 2,
    "Fortes pluies": 3,
    "Tempête": 4,
    "Ouragan": 5,
    "Autre": 6,
    "Ne sait pas": 7,
    "Hochwasser": 2,
    "Starkregen": 3,
    "Sturm": 4,
    "Hurrikan": 5,
    "Anderes": 6,
    "Weiß nicht": 7,
    "Inundación": 2,
    "Fuertes lluvias": 3,
    "Tormenta": 4,
    "Huracán": 5,
    "Otro": 6,
    "No sabe": 7
}