export default {
    "Pellet": { "type": 1, "category": 1, "language": "en" },
    "Degraded Fragment": { "type": 2, "category": 1, "language": "en" },
    "Angular Fragment": { "type": 3, "category": 1, "language": "en" },
    "Plastic Film Fragment": { "type": 4, "category": 2, "language": "en" },
    "Fiber Fragment": { "type": 5, "category": 3, "language": "en" },
    "Foam Fragment": { "type": 6, "category": 4, "language": "en" },
    "Expanded Polystyrene Fragment and Ball": { "type": 7, "category": 5, "language": "en" },
    "Granule": { "type": 1, "category": 1, "language": "fr" },
    "Fragment dégradé": { "type": 2, "category": 1, "language": "fr" },
    "Fragment angulaire": { "type": 3, "category": 1, "language": "fr" },
    "Fragment de film plastique": { "type": 4, "category": 2, "language": "fr" },
    "Fragment de fibre": { "type": 5, "category": 3, "language": "fr" },
    "Fragment de mousse": { "type": 6, "category": 4, "language": "fr" },
    "Fragment et balle de polystyrène expansé": { "type": 7, "category": 5, "language": "fr" },
    "Granulat": { "type": 1, "category": 1, "language": "de" },
    "Abgebauter Fragment": { "type": 2, "category": 1, "language": "de" },
    "Eckiger Fragment": { "type": 3, "category": 1, "language": "de" },
    "Fragment von Kunststofffolie": { "type": 4, "category": 2, "language": "de" },
    "Faserfragment": { "type": 5, "category": 3, "language": "de" },
    "Schaumfragment": { "type": 6, "category": 4, "language": "de" },
    "Fragment und Kugel aus expandiertem Polystyrol": { "type": 7, "category": 5, "language": "de" },
    "Gránulo": { "type": 1, "category": 1, "language": "es" },
    "Fragmento degradado": { "type": 2, "category": 1, "language": "es" },
    "Fragmento angular": { "type": 3, "category": 1, "language": "es" },
    "Fragmento de película plástica": { "type": 4, "category": 2, "language": "es" },
    "Fragmento de fibra": { "type": 5, "category": 3, "language": "es" },
    "Fragmento de espuma": { "type": 6, "category": 4, "language": "es" },
    "Fragmento y bola de poliestireno expandido": { "type": 7, "category": 5, "language": "es" }
}
