import EStyleSheet from 'react-native-extended-stylesheet';

export default styles = EStyleSheet.create({
    materialsModal: {
        view: {
            justifyContent: 'flex-end',
            margin: "0$rem",
            height: "100%",
        },
        container: {
            height: "90%",
            backgroundColor: "#ffffff",
            borderTopStartRadius: "25$rem",
            borderTopEndRadius: "25$rem",
            borderStyle: "solid",
            padding: "10$rem",
        },
        header: {
            width: '100%',
            height: "40%",
            fontSize: "10$rem",
            alignItems: "left",
            padding: "5$rem",
        },
        warningIcon: {
            alignSelf: "flex-start",
        },
        pageTitle: {
            width: 'auto',
            textAlign: 'left',
            fontSize: "26$rem",
            color: '#232348',
            fontWeight: 'bold'
        },
        pageSubTitle: {
            width: '95%',
            marginBottom: "10$rem",
            textAlign: 'left',
            fontSize: "20$rem",
            fontFamily: 'Roboto',
            color: '#232348',
        },
        titleText: {
            width: '100%',
            alignItems: 'flex-end',
            textAlign: 'center',
            fontSize: "16$rem",
            color: '#232348',
        },
        text: {
            width: '95%',
            textAlign: 'left',
            fontSize: "12$rem",
            color: '#232348',
        },
        body: {
            height: "43%",
            alignItems: 'center',
            width: '100%',
            padding: "5$rem",
            marginVertical: '5$rem',
        },
        scrollViewModal: {
            height: "100%",
            width: '100%',
            paddingHorizontal: "5$rem",
            marginVertical: '5$rem',
            borderRadius: "25$rem",
            borderStyle: "solid",
            backgroundColor: "hsl(240, 75%, 95%)",
            borderColor: "hsl(240, 75%, 70%)",
            borderWidth: "1$rem",
        },
        scrollViewContent: {
            rowGap: '15$rem',
            columnGap: '2$rem',
            justifyContent: "center",
            alignItems: "center",
            padding: "5$rem",
        },
        equipmentView: {
            width: "100%",
            maxHeight: "100$rem",
            justifyContent: "space-around",
            alignItems: "center",
            flexDirection: "row",
        },
        image: {
            alignItems: "center",
            justifyContent: "center",
        },
        description: {
            width: '55%',
            textAlign: 'left',
        },
        descriptionTitle: {
            fontWeight: 'bold',
            fontSize: "20$rem",
        },
        separator: {
            marginVertical: "3%",
            height: '2$rem',
            width: '85%',
            backgroundColor: '#ddd',
        },
        footer: {
            height: "15%",
            justifyContent: "space-around",
            alignItems: "center",
            padding: "5$rem",
            flexDirection: "column",
            marginVertical: "5$rem",
        },
        viewRow: {
            justifyContent: 'center',
            alignItems: 'center',
            flexDirection: 'row',
            width: '100%',
        },
        switchText: {
            textAlign: 'center',
            fontSize: "12$rem",
            color: '#232348',
        }
    },
    exitPopUpModal: {
        content: {
            height: "25%",
            backgroundColor: "#ffffff",
            borderRadius: "25$rem",
            borderColor: "#09295A",
            borderStyle: "solid",
            padding: "5$rem"
        },
        header: {
            height: "45%",
            fontSize: "10$rem",
            alignItems: "center",
            justifyContent: "center",
            marginVertical: '5$rem',
        },
        buttonColor: '#232348',
        confirmButtonColor: '#fff',
        confirmButton: {
            justifyContent: 'center',
            alignItems: 'center',
            width: '150$rem',
            height: '50$rem',
            borderRadius: '30$rem',
            borderStyle: 'solid',
            borderWidth: '3$rem',
            borderColor: '#09295A'
        },
        confirmButtonText: {
            fontSize: '18$rem',
            height: '100%',
            fontWeight: 'bold',
            alignSelf: 'center',
            textAlignVertical: 'center',
            color: '#09295A',
        },
        cancelButton: {
            justifyContent: 'center',
            alignItems: 'center',
            width: '150$rem',
            height: '50$rem',
            borderRadius: '30$rem',
            borderStyle: 'solid',
            padding: '5$rem'
        },
        cancelButtonText: {
            height: '100%',
            fontSize: '18$rem',
            fontWeight: 'bold',
            alignSelf: 'center',
            textAlignVertical: 'center',
            color: 'white',
        },
        text: {
            width: '100%',
            alignItems: 'flex-end',
            textAlign: 'center',
            fontSize: "20$rem",
            color: '#232348',
            fontWeight: 'bold',
            marginVertical: "3$rem"
        },
        subText: {
            width: '100%',
            alignItems: 'flex-end',
            textAlign: 'center',
            fontSize: "14$rem",
            color: '#232348',
        },
        body: {
            height: "30%",
            justifyContent: "center",
            alignItems: "center",
            paddingHorizontal: "5$rem",
            marginVertical: '5$rem',
        },
        footer: {
            height: "45%",
            justifyContent: "space-around",
            alignItems: "center",
            padding: "5$rem",
            flexDirection: "row",
            marginVertical: "5$rem",
        },
    },
    deleteAccountModal: {
        content: {
            height: "30%",
            backgroundColor: "#ffffff",
            borderRadius: "25$rem",
            borderColor: "#09295A",
            borderStyle: "solid",
            padding: "5$rem"
        },
        header: {
            width: '85%',
            height: "50%",
            fontSize: "10$rem",
            alignItems: "center",
            justifyContent: "center",
            marginLeft: '30$rem',
            marginTop: '10$rem',
        },
        buttonColor: '#ff6347',
        cancelButton: {
            justifyContent: 'center',
            alignItems: 'center',
            width: '150$rem',
            height: '50$rem',
            borderRadius: '25$rem',
            borderStyle: 'solid',
            borderColor: '#808080',
            borderWidth: '3$rem',
        },
        cancelButtonText: {
            height: '100%',
            fontSize: '18$rem',
            fontWeight: 'bold',
            alignSelf: 'center',
            textAlignVertical: 'center',
            color: '#808080',
        },
        deleteButton: {
            justifyContent: 'center',
            alignItems: 'center',
            width: '150$rem',
            height: '50$rem',
            borderRadius: '25$rem',
            borderStyle: 'solid',
            padding: '5$rem'
        },
        deleteButtonStyle: {
            borderRadius: '25$rem',
        },
        deleteButtonText: {
            height: '100%',
            fontSize: '18$rem',
            fontWeight: 'bold',
            alignSelf: 'center',
            textAlignVertical: 'center',
            color: '#fff',
        },
        text: {
            width: '100%',
            alignItems: 'flex-end',
            textAlign: 'left',
            fontSize: "22$rem",
            color: '#232348',
            fontWeight: '700',
            marginVertical: "3$rem"
        },
        subText: {
            width: '100%',
            alignItems: 'flex-end',
            textAlign: 'left',
            fontSize: "16$rem",
            color: '#232348',
        },
        body: {
            height: "30%",
            justifyContent: "center",
            alignItems: "center",
            paddingHorizontal: "5$rem",
            marginVertical: '5$rem',
        },
        footer: {
            height: "50%",
            justifyContent: "space-around",
            alignItems: "center",
            padding: "5$rem",
            flexDirection: "row",
            marginVertical: "5$rem",
        },
    }
});
